### ISSUE TITLE
Submitting new version to SSC

### ISSUE THREAD

**Issue by martacto** [surveycto/stata-scto#6]
- [x] 1. **Merge to *master*** - Merge all branches with the changes that should be included in the new version first to the `master` branch.
- [x] 2. **Update version and date** - Update the version number and date in all ado-files and all dates in all help files. See section below for details.
- [x] 3. **Create a .zip file** - Create a .zip file with all ado-files and help files in the **ado** and **help**. Do not include the folders, just the files in those folders.
- [x] 4. **Email Prof. Baum** - Email the .zip file to kit.baum@bc.edu.
    - If any commands are added or deleted, make note of that in the email.
    - If any meta information needs to be updated, include it according to the [instructions here](https://github.com/kbjarkefur/scto/blob/master/admin/ssc-description.md) in that email.
- [x] 5. **Draft release note** - Go to the [release notes](https://github.com/surveycto/scto/releases) and draft a new release note for the new version. Link to the [issues](https://github.com/surveycto/scto/issues) solved in this release.
- [x] 6. **Wait for publication confirmation** - Do not proceed past this step until Prof. Baum has confirmed that the new version is uploaded to the servers.
- [x] 7. **Publish release note** - Once the new version is up on SSC, publish the release note.
- [x] 8. **Close issues** - Close the issues which fix is now published on the SSC server.

**Comment by chrislrobert** [comment]
"**Merge to _develop_** - Merge all branches with the changes that should be included in the new version first to the master branch." The heading is "merge to develop" but then the instruction seems to be to merge to "master" — is one incorrect?

**Comment by chrislrobert** [comment]
"Link to the issues issues solved in this release." has "issues" twice.

**Comment by chrislrobert** [comment]
"Do not proceed pass this step" has "pass" instead of "past".

**Comment by chrislrobert** [comment]
I wasn't sure where this was getting published, and if it was our master checklist for all of time. In case it was, suggested some small tweaks above. Otherwise, looks great!

**Comment by martacto** [comment]
Thank you Chris,

I have used the checklist that was suggested here: https://github.com/surveycto/stata-scto/blob/master/admin/checklist-update-SSC.md. I guess it's our checklist for all of time.

The first action, however, is incorrect in my case. I did the reverse according to Gary's suggestion.
Should I change the Master checklist then?

**Comment by chrislrobert** [comment]
I would definitely make our checklist accurate to our case, yes. Thanks!
